devices:
  - name: "830-1"
    type: "lockin"
    model: "SR830"
    gpib:
      address: 10
      bus: 0
  - name: "830-2"
    type: "lockin"
    model: "SR830"
    gpib:
      string: "GPIB0::11::INSTR"
  - name: "830-3"
    type: "lockin"
    model: "SR830"
    gpib:
      string: "GPIB0::15::INSTR"
