devices:
  - name: "830-1"
    type: "lockin"
    model: "SR830"
    gpib:
      address: 7
      bus: 0
  - name: "830-2"
    type: "lockin"
    model: "SR830"
    gpib:
      string: "GPIB0::8::INSTR"
  - name: "HP"
    type: "sweeper"
    model: "HP83751A"
    gpib:
      address: 11
      bus: 0